### ISSUE TITLE
package install isn't working

### ISSUE THREAD

**Issue by christopherpryer** [christopherpryer/pyords#7]
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Chris\AppData\Local\Temp\pip-install-sh_bzsar\pyords\setup.py", line 10, in <module>
        with open('./requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
```

**Comment by christopherpryer** [comment]
note: file installed with -e . method because the file existed within the repository on my machine. for some reason its not being deployed.

**Comment by christopherpryer** [comment]
requirements.txt is not being bundled with the deployed package on pypi. need to look into this.

**Comment by christopherpryer** [comment]
Seems to be working.
